SELECT * FROM "MEMBER";
--1번부터 5번까지 데이터 가져오기
--rownum : 오라클리 제공하는 가상컬럼
SELECT *
FROM (SELECT rownum AS rnum, m.* 
	FROM (SELECT * FROM MEMBER M ORDER BY enrolldate DESC) m)
WHERE rnum BETWEEN 6 AND 10; 
--BETWEEN AND 사이의 값이 시작, 끝 rownum값이 들어가야한다

CREATE TABLE NOTICE(
        NOTICE_NO NUMBER PRIMARY KEY,
        NOTICE_TITLE VARCHAR2(100) NOT NULL,
        NOTICE_WRITER VARCHAR2(15) NOT NULL,
        NOTICE_CONTENT VARCHAR2(4000) NOT NULL,
        NOTICE_DATE DATE DEFAULT SYSDATE,
        FILEPATH VARCHAR2(300),
        STATUS VARCHAR2(1) DEFAULT 'Y',
        constraint fk_notice_writer FOREIGN KEY (NOTICE_WRITER) REFERENCES MEMBER (USERID)
    );



    CREATE SEQUENCE SEQ_NOTICE_NO;

    INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL,'공지사항테스트','admin','공지사항테스트입니다',default,null,default);
    INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL,'코로나 힘내자','admin','코로나가 없어지길.',default,null,default);
    COMMIT;
    SELECT * FROM NOTICE;
    DELETE FROM NOTICE WHERE notice_no=24;
    UPDATE NOTICE SET FILEPATH='file.png' WHERE NOTICE_NO=1;