CREATE TABLE BOARD_COMMENT(
        "BOARD_COMMENT_NO" NUMBER,
        "BOARD_COMMENT_LEVEL" NUMBER DEFAULT 1,
        "BOARD_COMMENT_WRITER" VARCHAR2(15), 
        "BOARD_COMMENT_CONTENT" VARCHAR2(2000), 
        "BOARD_REF" NUMBER, 
        "BOARD_COMMENT_REF" NUMBER, 
        "BOARD_COMMENT_DATE" DATE DEFAULT SYSDATE, 
        CONSTRAINT PK_BOARD_COMMENT_NO PRIMARY KEY(BOARD_COMMENT_NO),
        CONSTRAINT FK_BOARD_COMMENT_WRITER FOREIGN KEY(BOARD_COMMENT_WRITER) REFERENCES MEMBER(USERID) ON DELETE SET NULL,
        CONSTRAINT FK_BOARD_REF FOREIGN KEY(BOARD_REF) REFERENCES BOARD(BOARD_NO) ON DELETE CASCADE,
        CONSTRAINT FK_BOARD_COMMENT_REF FOREIGN KEY(BOARD_COMMENT_REF) REFERENCES BOARD_COMMENT(BOARD_COMMENT_NO) ON DELETE CASCADE
    );

    --DROP TABLE BOARD_COMMENT;

    COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_NO IS '게시판댓글번호';
    COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_LEVEL IS '게시판댓글 레벨';
    COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_WRITER IS '게시판댓글 작성자';
    COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_CONTENT IS '게시판댓글';
    COMMENT ON COLUMN BOARD_COMMENT.BOARD_REF IS '참조원글번호';
    COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_REF IS '게시판댓글 참조번호';
    COMMENT ON COLUMN BOARD_COMMENT.BOARD_COMMENT_DATE IS '게시판댓글 작성일';

        
    CREATE SEQUENCE SEQ_BOARD_COMMENT_NO
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    NOCACHE;
    
   
SELECT * FROM BOARD_COMMENT;

SELECT * FROM BOARD ORDER BY board_date DESC;
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, DEFAULT, 'opqr','글 잘읽었습니다.',144,NULL,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, DEFAULT, 'efgh','좋은 정보 감사합니다.',144,NULL,DEFAULT);

--대댓글추가 : 댓글번호를 참조해서 insert할 것
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'stuv','좋은 정보가 어디에...?',21,30,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'efgh','하하하...안보이시는구나...',21,30,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'wxyz','얼씨구..',21,28,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'wxyz','저는 보입니다.',21,30,DEFAULT);
INSERT INTO BOARD_COMMENT VALUES(SEQ_BOARD_COMMENT_NO.NEXTVAL, 2, 'hijk','뭐임....',21,28,DEFAULT);


  